name: Build-and-Publish-to-PyPI

on:
  push:
    branches:
      - main
      - master
  # or use `workflow_dispatch:` if you want manual triggers

jobs:
  build-publish:
    runs-on: ubuntu-latest

    # 1. Include the id-token: write permission so OIDC token can be issued
    permissions:
      contents: write
      id-token: write

    steps:
      # 2. Check out your code
      - name: Check out repository
        uses: actions/checkout@v4

      # 3. Set up Python (matching your version or a matrix)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # 4. Install Poetry & project dependencies
      - name: Install Poetry & deps
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install

      # 5. Build your package (creates ./dist/)
      - name: Build package
        run: |
          poetry build
          ls -la dist  # Debug: list what's in dist

      # 6. Publish to PyPI with the GitHub OIDC token
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}  # or your PyPI API token
          packages_dir: dist
          # verify_metadata: true  # optional, default: true
          # skip_existing: false   # optional
          # attestations: true     # optional
